# Generated by Django 4.2.8 on 2024-01-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('ram', models.DecimalField(decimal_places=0, max_digits=3)),
                ('rom', models.DecimalField(decimal_places=0, max_digits=3)),
                ('camera', models.DecimalField(decimal_places=0, max_digits=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
