# Generated by Django 4.2.8 on 2024-01-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopNest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rom',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
