# Generated by Django 4.2.8 on 2024-01-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopNest', '0002_alter_product_rom'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/loading.gif', upload_to='images/'),
        ),
    ]
