# Generated by Django 4.2.8 on 2024-01-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopNest', '0005_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Cart_Items',
        ),
    ]
