# Generated by Django 4.2.8 on 2024-01-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopNest', '0007_cart_products_delete_cart_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_products',
            new_name='Cart',
        ),
    ]
