# Generated by Django 4.2.8 on 2024-01-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopNest', '0008_rename_cart_products_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(default='static/loading.gif', upload_to=''),
        ),
    ]
