# Generated by Django 4.2.8 on 2024-01-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopNest', '0010_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('flat_no_building', models.CharField(max_length=255)),
                ('landmark', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('city_state', models.CharField(max_length=255)),
                ('pin_code', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
