# Generated by Django 4.2.8 on 2024-01-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopNest', '0012_alter_profile_city_state_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('order_id', models.IntegerField(null=True)),
                ('type', models.TextField(choices=[('p', 'password'), ('d', 'delivery'), ('o', 'other')])),
                ('query', models.TextField()),
            ],
        ),
    ]
