# Generated by Django 4.2.8 on 2024-01-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopNest', '0016_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='ratings',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
