# Generated by Django 4.2.8 on 2024-01-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopNest', '0017_reviews_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='ratings',
            field=models.DecimalField(decimal_places=1, max_digits=1),
        ),
    ]
