# Generated by Django 4.2.8 on 2024-01-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopNest', '0019_alter_reviews_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='ratings',
            field=models.IntegerField(),
        ),
    ]
